### ISSUE TITLE
The Contact Form Button is not in the center

### ISSUE THREAD

**Issue by annanyadas** [annanyadas/practice#13] opened 2021-06-09 04:24 UTC
Make the button in the center and the center should be maintained in  mobile view too

**Comment by ahcodes** [comment] 2021-06-09 14:47
Hi Ananya, I'd like to take care of this issue. Could you assign me, please? Thanks!

**Comment by annanyadas** [comment] 2021-06-09 17:16
i assigned it you . Go ahead

**Comment by GaurPeeyush** [comment] 2021-06-11 19:13
Contact button Issue is fixed.
Now button is center aligned.

**Comment by MathurUtkarsh** [comment] 2021-06-12 05:10
Contact button is now center aligned.
Issue Solved :)

**Comment by ahcodes** [comment] 2021-06-12 06:03
Reviewed the code, the button is center aligned.

**Comment by MathurUtkarsh** [comment] 2021-06-12 16:27
The issue has been solved so please merge my pull request .

**Comment by GaurPeeyush** [comment] 2021-06-17 08:43
The issue is fixed!
Glad that I could help
You may close this issue!
:)

**Closed as completed** 2021-06-17 10:57 UTC
Labels: good first issue
